void main(void)
{
 int &barman1 = create_sprite(344, 176, 0, 417, 4);
 sp_script(&barman1 "barman1");
 {
  say_stop_npc("`2My mama can cook wonderful dishes of food.", &current_sprite);
  wait(200);
  say_stop_npc("`5Oh yeah? My mama can make her dishes look like crap.", &barman1);
  wait(200);
  say_stop_npc("`2I take that as a challenge.", &current_sprite);
  wait(200);
  say("`5Yo mama is so...", &barman1);
  wait(10);
  say_stop_npc("`2Yo mama is so...", &current_sprite);
  wait(2000);
  say_stop_npc("`5On with the show...", &barman1);
  wait(200);
  talk:
  say_stop_npc("`2Yo Mama's so stupid she stole a free sample.", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo Mama's so stupid that when she saw a 'Wet Floor' sign, she did.", &barman1);
  wait(200);
  say_stop_npc("`2Damn, ok you won that one.", &current_sprite);
  say_stop_npc("`2Ok, here goes...", &current_sprite);
  say_stop_npc("`2Yo mama so lazy that she came in last place in a recent snail marathon.", &current_sprite);
  wait(200);
  say_stop_npc("`5Hahahaha!", &barman1);
  say_stop_npc("`5Shit.", &barman1);
  wait(200);
  say_stop_npc("`5You laughed! That makes me the winner.", &current_sprite);
  wait(1000);
  say_stop_npc("`2Yo mama has green hair and thinks she's a tree!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama has a glass eye with a fish in it!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama has so many freckles she looks like a hamburger!", &current_sprite);
    wait(200);
  say_stop_npc("`5Yo mama so ugly the government moved Halloween to her birthday!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama is so stupid she sits on the TV and watches the couch!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so stupid she put a quarter in a parking meter and waited for a gumball!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama is so fat she makes a whale look like a pimple on her ass!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so short she has to use a ladder to pick up a dime!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama head is so big it shows up on radar!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so ugly when she passes by, the toilet flushes!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama is so fat, when she stands on weighing scales it reads 'to be continued'!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat that people call her Moses, 'cause every time she steps in water it parts!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama's breath stinks so bad that every time she burps her teeth have to duck!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat that she was born on the 8th, 9th AND 10th of July!", &barman1);
  wait(200);
  say_stop_npc("`2Yo mama's cooking is so bad, the homeless give it back!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so stupid, when they said, 'Order in the court' she asked for fries and a shake!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so poor the ducks throw bread at her!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so ugly, her imaginary friend played with other kids!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so ugly when she went to the bathroom, she scared the shit out of the toilet!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat, she fell into a black hole and it clogged!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so ugly, even Hello Kitty said goodbye!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so old, she knew Burger King when he was still a prince!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so stupid, she tried to make an appointment with Dr.pepper!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat, she fell in love and broke it!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so ugly, the army doesn't use guns any more, they use her picture!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat, I took a picture of her last Christmas and it's still printing!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so fat, that when she fell, no one was laughing but the ground was cracking up. ", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so ugly, she made One Direction go another direction!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so stupid, she climbed over a glass wall to see what was on the other side!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so stupid she brought a spoon to the super bowl!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so fat, when she sat on an iPod, she made the iPad!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so ugly, when she took a bath the water jumped out!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama's teeth are so yellow, when she smiled at traffic, it slowed down!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so stupid, she put lipstick on her forehead to make up her mind!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so fat, she was baptized at SeaWorld!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so dumb, she went to the dentist to get a Bluetooth!", &barman1);
  wait(200);
    say_stop_npc("`2Yo mama is so fat, when God said 'Let there be light,' he asked her to move out of the way!", &current_sprite);
  wait(200);
  say_stop_npc("`5Yo mama is so fat, the aliens call her 'the mothership.'", &barman1);
  wait(200);
  goto talk;
  
 }
}